name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install
        run: npm i && npm i -g http-server @lhci/cli

      - name: Build
        run: npm run build

      - name: LighthouseCI
        run: lhci autorun
        env:
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}